[build]
command = "chmod +x build.sh && ./build.sh"
output_directory = "frontend/build"

[build.environment]
NODE_VERSION = "18"
NODE_ENV = "production"

[build.publish]
framework = "react"

[[routes]]
  pattern = "/*"
  handler = "static"
  options = { index = "index.html" }
