[build]
command = "cd frontend && npm install && npm run build"
output_directory = "frontend/build"

[build.environment]
NODE_VERSION = "18"
NODE_ENV = "production"
CI = "true"

[build.publish]
framework = "react"

[[routes]]
  pattern = "/*"
  handler = "static"
  options = { index = "index.html" }
